### ISSUE TITLE
v0.2.0 fails to compile (elixir v1.10.3, erlang/otp 22)

### ISSUE THREAD

**Issue by varunrau** [mindok/contex#21]
v0.2.0 of the library fails to compile for me running elixir v1.10.3 and erlang/otp 22. 

Stacktrace below:
```
==> contex
Compiling 17 files (.ex)

== Compilation error in file lib/chart/dataset.ex ==
** (CompileError) lib/chart/dataset.ex:61: type t/0 undefined (no such type in Contex.Dataset)
    (elixir 1.10.3) lib/kernel/typespec.ex:898: Kernel.Typespec.compile_error/2
    (elixir 1.10.3) lib/kernel/typespec.ex:937: Kernel.Typespec.fn_args/6
    (elixir 1.10.3) lib/kernel/typespec.ex:377: Kernel.Typespec.translate_spec/8
    (stdlib 3.12.1) lists.erl:1354: :lists.mapfoldl/3
    (elixir 1.10.3) lib/kernel/typespec.ex:229: Kernel.Typespec.translate_typespecs_for_module/2
    (elixir 1.10.3) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
could not compile dependency :contex, "mix compile" failed. You can recompile this dependency with "mix deps.compile contex", update it with "mix deps.update contex" or clean it with "mix deps.clean contex"
```

When using `v0.1.0`, the library is able to compile successfully.

**Comment by mindok** [comment]
Hi Varun, that’s fixed in master - the type handling became stricter in the Elixir v1.10 compiler vs v1.9. If you update your deps to point to the github repo you should be fine. Mix.exs in the Contex-samples repo has an example of how to do it if you’re not sure.

**Comment by varunrau** [comment]
Thanks, pointing to master worked!
